### PR TITLE
Display attributes boat selection screen

### PR DESCRIPTION
**Pull request by UmerFakher**
Umer Fakher

## v1.2.4 - Umer (24/1/2021)
- NFR_Attributes Extensions
- Added function that displays attribute value for a given BoatType in BoatSelectScreen
- Changed BoatSelectScreen displays attributes Health, Stamina, Agility & Speed for each BoatType
- Changed Rearranged DifficultySelectScreen buttons

### CODE REVIEW

**Comment by UmerFakher** [comment]
#### BoatSelectionScreen
BoatSelectionScreen

#### DifficultySelectionScreen
DifficultySelectionScreen

**Comment by UmerFakher** [comment]
If there is anything else GUI based perhaps include in this pull request.


Tests have been run individually and work. No collective test running yet so when this is done can try it on this.

**Comment by UmerFakher** [comment]
BoatSelectScreen parameters tuned. Should display as intended in available space on screen.

**Review by wpw503 — APPROVED** [review]

**Comment by UmerFakher** [comment]
Newest BoatSelectionScreen: image

**Pull request merged**
